GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUwLCJlbWFpbCI6InNhbUBzYW0uY29tIiwiaWF0IjoxNjU2Njk4NjczfQ.o-3Kqd3lVma0_WUIknyPSSc5ZRD-5Gy-nKZZ10BzFeg
###
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json

{
    "email": "sam@sam.com",
    "password": "123456"
}
###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json

{
    "email": "sam@sam.com",
    "password": "123456"
}